#Deriving the latest base image
FROM python:latest


#Labels as key value pair
LABEL Maintainer="Elegond"


# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /usr/app/src

#to COPY the remote file at working directory in container
#COPY checkts.py ./
COPY requirements.txt ./
# Now the structure looks like this '/usr/app/src/test.py'
RUN pip install --no-cache-dir -r requirements.txt

COPY checkts.py ./

#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

CMD [ "python", "./checkts.py"]
